### PR TITLE
Update docker compose

### PR DESCRIPTION
**Pull request by a-magdy**
- Update `docker-compose`, by sending the source code as a volume, to ease developing using docker.
- ~~Add `start` script in package.json, adding a script that install npm modules if not found.~~
- ~~Add `package-lock.json` file~~

### CODE REVIEW

**Comment by jakearchibald** [comment]
Unless I'm misunderstanding, `npm start` will fail on windows.

**Comment by s-slavchev** [comment]
`npm start` test results:
- does not work in Command Prompt _(Windows  10)_
- does not work in Windows PowerShell _(Windows  10)_
- works in Git Bash _(Windows  10)_

**Comment by a-magdy** [comment]
Ooops, I didn't consider windows!

.. well I could remove the `start` script from `package.json` to avoid confusion, and leave `start.sh` to be executed in the docker-compose, would that be an acceptable solution?

**Comment by s-slavchev** [comment]
@a-magdy I personaly see no reason to have the start.sh in the project.

On the other hand I find the new docker-compose very useful. Tested on Ubuntu 16.04 LTS and works fine - witter service looks properly configured, the volume is properly mapped, the watcher is working just fine picking up the file changes...

My two cents
- docker-compose.yml changes should be kept
- package-lock.json will be trouble for many students. In the course there is a lot of `git reset --hard` and `git checkout branch` and if someone generates his own package-lock.json _(some people change package versions inside package.json to make the code work on their environment)_ switching between branches can be tricky for some

**Comment by a-magdy** [comment]
Thanks @s-slavchev for your comment :)

- there is no need for start.sh

  * I get your point, it might be a little bit confusing, .. it could be written as a one line command in docker-compose as well!, but it won't look nice! .. I could rename it to `.start.sh` so it would be hidden by default, and users won't have to worry about it!

- package-lock.json will be trouble for many students

   * You are right about that also! .. will remove it

**Comment by a-magdy** [comment]
@s-slavchev @jakearchibald I updated the code to avoid any conflicts, and the changes so far are:

- Updated:
  * `docker-compose.yml` command to be inline
  * `README.md` ports configuration using docker-compose section & added a troubleshooting node-sass line
- Removed:
  * `start` script from package.json
  * `start.sh` script
  * `package-lock.json`

**Comment by jakearchibald** [comment]
@a-magdy thanks for this! Can you move the local-machine instructions above the docker ones? Generally I'd rather they tried that first. Cheers!

**Comment by a-magdy** [comment]
@jakearchibald Done :)

**Comment by jakearchibald** [comment]
Merged, thank you!

**Pull request merged**
